apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: ecommerce-website
spec:
  type: LoadBalancer  # Specifies that this Service is of type LoadBalancer
  ports:
    - port: 80        # Port that the service will expose to the internet
      targetPort: 80   # Port that the web application container listens to
  selector:
    app: ecommerce-website  # Selector to match pods with this label in the Deployment