name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-web:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecom-web:latest

      # Set up kubectl (alternative setup action)
      - name: Set up kubectl
        uses: actions/setup-kubectl@v2
        with:
          version: 'v1.18.0'

      # Set KUBECONFIG (if using KUBECONFIG secret)
      - name: Set KUBECONFIG
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      # Update Kubernetes deployment
      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/website-deployment ecommerce-website=${{ secrets.DOCKER_USERNAME }}/ecom-web:latest
          kubectl rollout status deployment/website-deployment
